name: Frontend/CI/Format
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ./frontend/**
  push:
    branches:
      - master
    paths:
      - ./frontend/**
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Check formatting
        working-directory: ./frontend
        run: npm run format:check
